### ISSUE TITLE
The installer will not accept a /21 netmask

### ISSUE THREAD

**Issue by zunder1990** [seijikun/lapas#1]
I am trying to install on VM with a single NIC that is connected to a established network. When I tired to use 10.102.0.20/21 the install will not accept the input.

root@lapas:/data# cat /etc/debian_version
11.6
root@lapas:/data#

![lapas-ip-error1](https://user-images.githubusercontent.com/11825392/230429259-4fe94bfe-af74-4f14-af79-502e67750540.PNG)
![lapas-ip-error2](https://user-images.githubusercontent.com/11825392/230429315-93240273-5df5-4c55-92ba-97ac492dde4d.PNG)
![image](https://user-images.githubusercontent.com/11825392/230429525-318d553e-4686-4d80-be44-e585c70b6f43.png)

**Comment by zunder1990** [comment]
correction, after running the installer a 2nd time. It will accept a /21 but the .1 IP. This hardcoded value should be allowed to be changed.

**Comment by seijikun** [comment]
Yes, unfortunately I know of this limitation.
The origin of this limitation is that getting subnet calculations right is hard enough with proper programming languages, but doing bit masking etc. with bash scripts (at least as far as I know) is downright impossible..

The calculations that would need to be done:

- Convert between `/24` notation to `255.255.255.0` notation. (**That is done**)
- Calculate the proper subnet address from a fully specified IP address (e.g. `192.168.42.10/24` to subnet address `192.168.42.0`)
- Within the specified subnet, calculate a range of addresses for the DHCP server to assign to clients (subnet address `192.168.42.0/24` to something like `192.168.42.10 - 192.168.42.254`)

To be honest, I'm not sure on a good way forward here...
It may be a possibility to have a python script that does these calculations.

The workaround for now is to install with a `/24` but with the correct IP-Address, then change the configuration on the running instance aftwards in: (from the top of my head)
- `<installFolder>/scripts/config`
- `/etc/dhcp/dhcpd.conf`
- `/etc/systemd/network/20-upstream.network`

I'll think about an idea for how to best do this

**Comment by seijikun** [comment]
I just wrote a bunch of [helper functions](https://github.com/seijikun/lapas/blob/436b4ea166c2911cb48e8d072ca7e49aa1458c04/src/helpers/ipcalc.sh) to do the calculations by spawning 4-line python scripts that do the calculation :man_shrugging: 

For reference, this is what is calculated for your `10.102.0.20/21` now:
![image](https://user-images.githubusercontent.com/820845/230685545-de3aff7d-2f6f-4269-981b-94014c329b88.png)

Please let me know if something doesn't work as expected!
(Didn't do a new release yet, so you have to use the nightly)
